# Run initialization
/run/initialize
/run/setCut 0.01 mm

# ISO source
/gps/pos/type Surface
/gps/pos/centre 76.8 0. -74.4 cm
/gps/ang/type cos
/gps/pos/shape Sphere
/gps/pos/radius 3000 cm
/gps/ang/surfnorm true
#/gps/ang/mintheta 10 deg
/gps/ang/maxtheta 1.528 deg

# Particle type
/gps/particle proton
#/gps/ion 26 56
# Monoenergetic spectrum
/gps/energy 100 GeV
#/gps/ene/type Pow
#/gps/ene/min 100 GeV
#/gps/ene/max 100 TeV
#/gps/ene/alpha -1
#100 Gev, 10 Tev
/run/beamOn 250
